version: "3.8"

services:
  my-mysql:
    build:
      context: ./my-mysql/
      dockerfile: Dockerfile
    container_name: my-mysql
    environment:
      MYSQL_USER: app_user
      MYSQL_ROOT_PASSWORD: 221683
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p221683"]
      timeout: 30s
      retries: 10
      interval: 10s
      start_period: 40s
  
  my-gen:
    build:
      context: ./my-gen/
      dockerfile: Dockerfile
    environment:
      DB_URL: mysql+pymysql://root:221683@my-mysql:3306/app
    depends_on:
      my-mysql:
        condition: service_healthy
  