# Extension fields
x-redash-service: &redash-service
  image: redash/redash:25.8.0
  environment:
    REDASH_DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    REDASH_COOKIE_SECRET: 78787878
    REDASH_SECRET_KEY: 88005553535
    REDASH_REDIS_URL: redis://redis:6379/0
    PYTHONUNBUFFERED: 0
    REDASH_LOG_LEVEL: INFO
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - redash-network
  restart: unless-stopped

# Services
services:
  # Database services
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - redash_postgres_data:/var/lib/postgresql/data
    networks:
      - redash-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redash_redis_data:/data
    networks:
      - redash-network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped

  my-mysql:
    build:
      context: ./my-mysql/
      dockerfile: Dockerfile
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 221683
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - redash-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p221683"]
      timeout: 30s
      retries: 10
      interval: 10s
      start_period: 40s

  # Redash services
  redash-server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"

  redash-worker:
    <<: *redash-service
    command: worker

  # Custom application services
  my-gen:
    build:
      context: ./my-gen/
      dockerfile: Dockerfile
    container_name: my-gen
    environment:
      DB_URL: mysql+pymysql://root:221683@my-mysql:3306/app
    depends_on:
      my-mysql:
        condition: service_healthy
    networks:
      - redash-network

# Network configuration
networks:
  redash-network:
    driver: bridge

# Volume configuration
volumes:
  redash_postgres_data:
  redash_redis_data:
  mysql_data: